#-------------------------------
# General Site Settings
title: My Writings
logo: logo.png # You can add own logo.
description: I write about my thoughts, I complaint about things.


#-------------------------------
# Author Settings
author:
  name: GuoXian Ho
  image: profile.jpg
  say-hello: Hello, I’m <strong>Ho Guo Xian</strong>
  bio: I write about <strong>thoughts</strong>, I complaint about <strong>things</strong>. 

#-------------------------------
# Contact links
twitter: https://twitter.com/daretobacon # Add your Twitter handle
instagram: https://instagram.com/hgx197 # Add your Instagram handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: sample # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: UA-156432299-1 # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
